### ISSUE TITLE
[Enhancement-Idea] Using MinHook

### ISSUE THREAD

**Issue by Tr1NgleDev** [4dMinerCommunity/mod-api#1]
You can use MinHook to hook some functions and other stuff.
just try it.

**Comment by Tr1NgleDev** [comment]
`idk if this mod api is actually mod api so you can add it as headers so this suggestion may not work `

**Comment by ghost** [comment]
the mod api is a single header rn, so think this will work!

edit, this wont work. i need stuff that is crossplatform (linux, and windows), i have found this tho https://www.codeproject.com/Articles/1100579/PolyHook-The-Cplusplus-x-x-Hooking-Library
